### ISSUE TITLE
Reproducibility Issue

### ISSUE THREAD

**Issue by zeroshu** [zhangcen456/IB#2]
Can you briefly introduce the running instructions? I can't reproduce your results.

**Comment by zhangcen456** [comment]
you can change the dimensionality of hidden layers using "-hd" or "--hidden_size" and change beta using '-b' or '--beta'. For example, for SST-2 dataset you may run "python model.py -h 150 -b 1.5 -as 0" ("-as 0" for not applying adversarial training). The hyper-parameter we used can be found in the paper.
